language: rust
rust:
  - nightly-2019-06-24
cache: cargo
script:
  - cargo build --release
  - ls $TRAVIS_BUILD_DIR/target/release/
before_deploy:
  # Set up git user name and tag this commit
  - git config --local user.name "Johann Woelper"
  - git config --local user.email "woelper@gmail.com"
  #- export TRAVIS_TAG=${TRAVIS_TAG:-$(date +'%Y%m%d%H%M%S')}
  - git tag $TRAVIS_OS_NAME$(date +'%Y%m%d%H%M%S')