[package]
name = "oculante"
version = "0.5.3"
authors = ["Johann Woelper <woelper@gmail.com>"]
edition = "2018"
license = "MIT"
repository = "https://github.com/woelper/oculante/"
description = "A minimalistic image viewer with analysis tools"
readme = "README.md"
keywords = ["graphics", "image", "viewer"]

[package.metadata.bundle]
name = "oculante"
identifier = "com.github.woelper.oculante"
icon = ["res/logo.png"]

[dependencies]
piston_window = "0.117.0"
clap = "2.33.3"
image = "0.23.12"
nalgebra = "0.24.0"
dds-rs = "0.7.0"
rgb = "0.8.25"
psd = "0.1.9"
exr = "0.9.0"
gif-dispose = "2.4.0"
nsvg = "0.5.1"
gif = "0.10.3"
lazy_static = "1.4.0"
libwebp-sys = "0.3"
self_update = "0.23.0"
# piston2d-gfx_graphics = "*"
# gfx_device_gl = "0.16.2"
splines = "*"

[target.'cfg(windows)'.build-dependencies]
# this currently causes a link error LNK1356, check in the future if the problem was solved
windres = "0.2.1"

[profile.release]
incremental = true
lto = true

[profile.dev]
incremental = true
debug = false
