[package]
name = "oculante"
version = "0.5.11"
authors = ["Johann Woelper <woelper@gmail.com>"]
edition = "2018"
license = "MIT"
repository = "https://github.com/woelper/oculante/"
description = "A minimalistic image viewer with analysis tools"
readme = "README.md"
keywords = ["graphics", "image", "viewer"]

[package.metadata.bundle]
name = "oculante"
identifier = "com.github.woelper.oculante"
icon = ["res/logo.png"]

[dependencies]
piston_window = "0.120.0"
clap = "2.33.3"
image = "0.23.13"
nalgebra = "0.28.0"
dds-rs = "0.7.0"
rgb = "0.8.25"
psd = "0.1.9"
exr = "0.9.0"
gif-dispose = "2.4.0"
gif = "0.10.3"
lazy_static = "1.4.0"
libwebp-sys = "0.4.0"
self_update = "0.27.0"
splines = "4.0.0"
log = "0.4.14"
simple-logging = "2.0.2"
usvg = "0.14.0"
resvg = "0.14.0"
tiny-skia = "0.5.1"

[target.'cfg(target_os = "macos")'.dependencies]
fruitbasket = { git = "https://github.com/woelper/fruitbasket", branch = "open-file-support" }

[target.'cfg(windows)'.build-dependencies]
# this currently causes a link error LNK1356, check in the future if the problem was solved
windres = "0.2.1"

[profile.release]
incremental = true
lto = true
codegen-units = 1

[profile.dev]
incremental = true
debug = false
opt-level = 1
