[package]
name = "oculante"
version = "0.1.1"
authors = ["Johann Woelper <woelper@gmail.com>"]
edition = "2018"

[dependencies]
piston_window = "*"
clap = "*"
image = "*"
nalgebra = "*"
dds-rs = "0.7.0"
rgb = "*"
psd = "0.1.4"
rs-exr = {git = "https://github.com/johannesvollmer/rs-exr.git"}


[target.'cfg(windows)'.build-dependencies]
windres = "0.2"