[package]
name = "oculante"
version = "0.4.5"
authors = ["Johann Woelper <woelper@gmail.com>"]
edition = "2018"
license = "MIT"
repository = "https://github.com/woelper/oculante/"
description = "A minimalistic image viewer with analysis tools"
readme = "README.md"
keywords = ["graphics", "image", "viewer"]

[package.metadata.bundle]
name = "oculante"
identifier = "com.github.woelper.oculante"
icon = ["res/logo.png"]

[dependencies]
piston_window = "0.112.0"
clap = "2.33.3"
image = "0.23.9"
nalgebra = "0.22.0"
dds-rs = "0.7.0"
rgb = "0.8.25"
psd = "0.1.9"
#exr = {git = "https://github.com/johannesvollmer/exrs.git"}
exr = "0.9.0"
gif-dispose = "2.4.1"
nsvg = "0.5.1"
gif = "0.10.3"
piston2d-graphics = "0.37.0"
#gfx_device_gl = "*"
# piston-gfx_texture = "0.41.0"
# pistoncore-glfw_window = "0.66.0"
# pistoncore-glutin_window = "*"
lazy_static = "*"
# [dependencies.pistoncore-sdl2_window]
# git = "https://github.com/PistonDevelopers/sdl2_window"

#[dependencies.pistoncore-glutin_window]
#git = "https://github.com/PistonDevelopers/glutin_window"

[target.'cfg(windows)'.build-dependencies]
# this currently causes a link error LNK1356, check in the future if the problem was solved
windres = "0.2.1"

[profile.release]
lto = true
