[package]
name = "oculante"
version = "0.1.3"
authors = ["Johann Woelper <woelper@gmail.com>"]
edition = "2018"

[dependencies]
piston_window = "*"
clap = "*"
image = "*"
nalgebra = "*"
dds-rs = "*"
rgb = "*"
psd = "*"
exr = {git = "https://github.com/johannesvollmer/exrs.git"}


[target.'cfg(windows)'.build-dependencies]
windres = "0.2"
