[package]
name = "oculante"
version = "0.2.2"
authors = ["Johann Woelper <woelper@gmail.com>"]
edition = "2018"

[dependencies]
piston_window = "*"
clap = "*"
image = "0.23.5"
nalgebra = "*"
dds-rs = "*"
rgb = "*"
psd = "*"
#exr = {git = "https://github.com/johannesvollmer/exrs.git"}
exr = "*"
gif-dispose = "*"
nsvg = "*"
gif = "*"
piston2d-graphics = "0.36.0"

# pistoncore-glutin_window = "*"

# [dependencies.pistoncore-sdl2_window]
# git = "https://github.com/PistonDevelopers/sdl2_window"

#[dependencies.pistoncore-glutin_window]
#git = "https://github.com/PistonDevelopers/glutin_window"

[target.'cfg(windows)'.build-dependencies]
windres = "0.2"

[profile.release]
lto = true

[package.metadata.bundle]
name = "oculante"
identifier = "com.github.woelper.oculante"
icon = ["res/logo.png"]