[package]
authors = ["Johann Woelper <woelper@gmail.com>"]
description = "A minimalistic image viewer with analysis and editing tools"
edition = "2018"
keywords = ["graphics", "image", "viewer"]
license = "MIT"
name = "oculante"
readme = "README.md"
repository = "https://github.com/woelper/oculante/"
version = "0.6.2"

[package.metadata.bundle]
icon = ["res/oculante.png"]
identifier = "com.github.woelper.oculante"
name = "oculante"

[dependencies]
clap = "3.2.16"
dds-rs = "0.7.0"
exr = "1.4.2"
image = "0.24.3"
lazy_static = "1.4.0"
libwebp-sys = "0.6.0"
log = "0.4.17"
nalgebra = "0.31"
psd = "0.3.3"
rgb = "0.8.33"
self_update = "0.30.0"
# simple-logging = "2.0.2"
anyhow = "1.0.57"
arboard = "2.1.1"
env_logger = "0.9.0"
notan = {version = "0.6", features = ["drop_files", "egui"]}
palette = "0.6"
rand = "0.8.5"
rand_chacha = "0.3.1"
rayon = "1.5.3"
resvg = "0.23.0"
strum = {version = "0.24", features = ["derive"]}
strum_macros = "0.24"
tiny-skia = "0.6.4"
usvg = "0.23.0"

[target.'cfg(target_os = "macos")'.dependencies]
fruitbasket = "0.10.0"

[target.'cfg(windows)'.build-dependencies]
# this currently causes a link error LNK1356, check in the future if the problem was solved
windres = "0.2.1"

[build-dependencies]
env_logger = "0.9.0"
log = "0.4.14"

[profile.release]
codegen-units = 1
incremental = true
lto = "thin"
strip = true
# opt-level = "z"
panic = "abort"

[profile.dev]
debug = false
incremental = true
opt-level = 1
