[package]
name = "oculante"
version = "0.5.15"
authors = ["Johann Woelper <woelper@gmail.com>"]
edition = "2018"
license = "MIT"
repository = "https://github.com/woelper/oculante/"
description = "A minimalistic image viewer with analysis tools"
readme = "README.md"
keywords = ["graphics", "image", "viewer"]

[package.metadata.bundle]
name = "oculante"
identifier = "com.github.woelper.oculante"
icon = ["res/logo.png"]

[dependencies]
piston_window = "0.121.0"
clap = "2.34"
image = "0.23.14"
nalgebra = "0.29.0"
dds-rs = "0.7.0"
rgb = "0.8.30"
psd = "0.3.0"
exr = "1.4.1"
gif-dispose = "2.4.0"
gif = "0.10.3"
lazy_static = "1.4.0"
libwebp-sys = "0.4.2"
self_update = "0.27.0"
splines = "4.0"
log = "0.4.14"
simple-logging = "2.0.2"
usvg = "0.19.0"
resvg = "0.19.0"
tiny-skia = "0.6.1"
env_logger = "0.9.0"
anyhow = "1.0.42"

[target.'cfg(target_os = "macos")'.dependencies]
fruitbasket = { git = "https://github.com/woelper/fruitbasket", branch = "open-file-support" }

[target.'cfg(windows)'.build-dependencies]
# this currently causes a link error LNK1356, check in the future if the problem was solved
windres = "0.2.1"

[profile.release]
incremental = true
lto = true
codegen-units = 1

[profile.dev]
incremental = true
debug = false
opt-level = 1
