name: NetBSD build test

on: [push]

jobs:
  test:
    runs-on: macos-12
    name: Test in NetBSD
    env:
      MYTOKEN : ${{ secrets.MYTOKEN }}
      MYTOKEN2: "value2"
    steps:
    - uses: actions/checkout@v2
    - name: Test in NetBSD
      id: test
      uses: vmactions/netbsd-vm@v0
      with:
        envs: 'MYTOKEN MYTOKEN2'
        usesh: true
        prepare: |
          uname -a
          pkg_add curl
          PKG_PATH="http://cdn.NetBSD.org/pub/pkgsrc/packages/NetBSD/$(uname -p)/$(uname -r|cut -f '1 2' -d.)/All/"
          export PKG_PATH
          # pkg_add pkgin
          # cat /usr/pkg/etc/pkgin/repositories.conf
          # pkgin search rust
          curl https://sh.rustup.rs -sSf | sh -s -- -y --default-toolchain nightly
          echo $SHELL
          # chmod +x "$HOME/.cargo/env"
          # eval "$HOME/.cargo/env"
          # which cargo
        run: |
          PATH=$HOME/.cargo/bin:$PATH
          export PATH
          cargo check
