on: [push]

name: build

jobs:
  check:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2

      - name: Install deps
        run: sudo apt-get install libxcb-shape0-dev libxcb-xfixes0-dev libasound2-dev nasm
        if: matrix.os == 'ubuntu-latest'

      - name: Run cargo check
        uses: actions-rs/cargo@v1
        with:
          command: check
