name: Rust

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
      with:
        profile: minimal
        toolchain: nightly 
    - name: Build
      run: cargo build
      with:
        profile: minimal
        toolchain: nightly
    - name: Run tests
      run: cargo test
      with:
        profile: minimal
        toolchain: nightly
